name: AWS

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials for stage account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.STAGE_AWS_SECRET_KEY_ID }}
        aws-secret-access-key: ${{ secrets.STAGE_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Test aws cli
      run: |
        aws s3 ls
