name: Build & deploy

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Run stage build
        if: github.ref == 'refs/heads/stage'
        #run: CONTRACT_ADDRESS=${CONTRACT_ADDRESS} yarn build
        run: echo "contract address is ${STAGE_CONTRACT_ADDRESS}"
        env:
          CONTRACT_ADDRESS: ${{ env.STAGE_CONTRACT_ADDRESS }}
